SHOW DATABASES;

CREATE DATABASE DB_GERENCIAMENTO;
USE DB_GERENCIAMENTO;
SHOW TABLES;

CREATE TABLE TB_ACESSO(
	USUARIO_ACESSO VARCHAR(40)  UNIQUE,
    SENHA_ACESSO   VARCHAR(128) NOT NULL,
    PRIMARY KEY(USUARIO_ACESSO)
);
DESCRIBE TB_ACESSO;
SELECT * FROM TB_ACESSO;
INSERT INTO TB_ACESSO VALUES ('adm', 123);

CREATE TABLE TB_PARCEIROS(
    CNPJ_PARCEIROS 		    CHAR(14)    NOT NULL,
	RAZAO_SOCIAL_PARCEIROS  VARCHAR(60) NOT NULL UNIQUE,
    DATA_INCLUSAO_PARCEIROS DATETIME    NOT NULL,
    PRIMARY KEY(CNPJ_PARCEIROS)
);
DESCRIBE TB_PARCEIROS;
SELECT * FROM TB_PARCEIROS;

CREATE TABLE TB_VENDAS(
    CNPJ_VENDAS      CHAR(14)     NOT NULL,
	COD_PROD_VENDAS  CHAR(15),
    NOME_PROD_VENDAS VARCHAR(60)  NOT NULL,
    DATA_VENDAS      DATETIME     NOT NULL,
    LOTE_VENDAS      CHAR(15)     NOT NULL,
    VALIDADE_VENDAS  DATETIME     NOT NULL,
    PRECO_VENDAS     DECIMAL(8,2) NOT NULL,
    EQUIPE_VENDAS    CHAR(1)      NOT NULL,
    PRIMARY KEY(COD_PROD_VENDAS)
);
DESCRIBE TB_VENDAS;
SELECT * FROM TB_VENDAS;

CREATE TABLE TB_COMPRAS(
	CNPJ_COMPRAS      CHAR(14),
    COD_PROD_COMPRAS  CHAR(15),
    NOME_PROD_COMPRAS VARCHAR(60)  NOT NULL,
    DATA_COMPRAS      DATETIME     NOT NULL,
    LOTE_COMPRAS      CHAR(15)     NOT NULL,
    VALIDADE_COMPRAS  DATETIME     NOT NULL,
    PRECO_COMPRAS     DECIMAL(8,2) NOT NULL,
    PRIMARY KEY(COD_PROD_COMPRAS)
);
DESCRIBE TB_COMPRAS;
SELECT * FROM TB_COMPRAS;

CREATE TABLE TB_ESTOQUE(
	CNPJ_ESTOQUE      CHAR(14)     NOT NULL,
    COD_PROD_ESTOQUE  CHAR(15),
    NOME_PROD_ESTOQUE VARCHAR(15)  NOT NULL,
    DATA_ESTOQUE      DATETIME     NOT NULL,
    LOTE_ESTOQUE      CHAR(15)     NOT NULL,
    VALIDADE_ESTOQUE  DATETIME     NOT NULL,
    PRECO_ESTOQUE     DECIMAL(8,2) NOT NULL,
    PRIMARY KEY(COD_PROD_ESTOQUE)
);
DESCRIBE TB_ESTOQUE;
SELECT * FROM TB_ESTOQUE;